### ISSUE TITLE
Echo server is not working

### ISSUE THREAD

**Issue by pum-purum-pum-pum** [snapview/tokio-tungstenite#83]
Reproduce:
In  browser console: `var exampleSocket = new WebSocket("ws://127.0.0.1:8080");`

Server logs:
```
thread 'main' panicked at 'Error during the websocket handshake occurred: Io(Custom { kind: Other, error: "No \"Connection: upgrade\" in client request" })', src/libcore/result.rs:1192:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1057
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:195
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:215
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:463
  11: rust_begin_unwind
             at src/libstd/panicking.rs:371
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1192
  14: core::result::Result<T,E>::expect
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libcore/result.rs:991
  15: echo_server::accept_connection::{{closure}}
             at examples/echo-server.rs:42
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/future.rs:43
  17: tokio::task::core::Core<T>::poll
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/core.rs:128
  18: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:120
  19: core::ops::function::FnOnce::call_once
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libcore/ops/function.rs:232
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/panic.rs:318
  21: std::panicking::try::do_call
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/panicking.rs:296
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  23: std::panicking::try
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/panicking.rs:272
  24: std::panic::catch_unwind
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/panic.rs:394
  25: tokio::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:101
  26: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/loom/std/causal_cell.rs:41
  27: tokio::task::harness::Harness<T,S>::poll
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:100
  28: tokio::task::raw::poll
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/raw.rs:162
  29: tokio::task::raw::RawTask::poll
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/raw.rs:113
  30: tokio::task::Task<S>::run
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/mod.rs:381
  31: tokio::runtime::basic_scheduler::SchedulerPriv::tick
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:192
  32: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:142
  33: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:411
  34: tokio::runtime::context::enter
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  35: tokio::runtime::handle::Handle::enter
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  36: tokio::runtime::Runtime::block_on
             at /home/vlad/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  37: echo_server::main
             at examples/echo-server.rs:17
  38: std::rt::lang_start::{{closure}}
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/rt.rs:67
  39: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  40: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  41: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:79
  42: std::panicking::try
             at src/libstd/panicking.rs:272
  43: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  44: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  45: std::rt::lang_start
             at /rustc/85976442558bf2d09cec3aa49c9c9ba86fb15c1f/src/libstd/rt.rs:67
  46: main
  47: __libc_start_main
  48: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by agalakhov** [comment]
Did you test it with Firefox? Please retest with the actual master version.

**Comment by pum-purum-pum-pum** [comment]
Yes, with firefox. Tested with both actual master version and crates.io.
Tested with gchrome -- it's working.

**Comment by agalakhov** [comment]
Please look at  https://github.com/snapview/tungstenite-rs/pull/106#

**Comment by agalakhov** [comment]
Please make sure you tested it WITH the PR mentioned above already merged. If not, please update and retest.

**Comment by pum-purum-pum-pum** [comment]
Ok it's working if I add: 
 ```[dependencies.tungstenite]
git = "https://github.com/snapview/tungstenite-rs.git"
default-features = false
``` in Cargo.toml

Thank you and sorry for inconvenience.

**Comment by agalakhov** [comment]
I'll release a updated version fixing this issue, thank you.

**Comment by application-developer-DA** [comment]
I believe this has already been published, hence closing the issue. Feel free to reopen if it appears again.
